# Inventaire simple : liste des serveurs à gérer
all:
  vars:
    # Variables communes à tous les serveurs
    ansible_connection: docker
    ansible_user: root
    #ansible_python_interpreter: /opt/homebrew/bin/python3

  hosts:
    # Serveur web
    web01:
      ansible_host: ansible-lab-web01

# hosts direct = inventaire simple
# children = inventaire structuré avec groupes
# Les deux sont valides. Vous choissisez selon la complexité de votre infra.
