# Inventaire PRODUCTION
all: # Groupe racine contenant tous les serveurs
  vars: # Variables communes à tous les serveurs production
    ansible_connection: docker # Type de connexion : Docker (pour environnement lab)
    ansible_user: root # Utilisateur de connexion : root
    #ansible_python_interpreter: /usr/bin/python3 # Interpréteur Python sur les hôtes cibles
    env: production # Variable d'environnement : production

  children: # Sous-groupes organisés par environnement
    production: # Groupe production
      children: # Sous-groupes fonctionnels dans production
        webservers: # Groupe des serveurs web
          hosts: # Liste des serveurs web (redondance pour HA)
            web01: # Premier serveur web
              ansible_host: ansible-lab-web01 # Nom du conteneur Docker
            web02: # Deuxième serveur web (haute disponibilité)
              ansible_host: ansible-lab-web02 # Nom du conteneur Docker
        
        appservers: # Groupe des serveurs d'application
          hosts: # Liste des serveurs d'application (redondance pour HA)
            app01: # Premier serveur d'application
              ansible_host: ansible-lab-app01 # Nom du conteneur Docker
            app02: # Deuxième serveur d'application (haute disponibilité)
              ansible_host: ansible-lab-app02 # Nom du conteneur Docker
        
        databases: # Groupe des serveurs de base de données
          hosts: # Liste des serveurs de base de données
            db01: # Premier serveur de base de données
              ansible_host: ansible-lab-db01 # Nom du conteneur Docker
        
        monitoring: # Groupe des serveurs de monitoring
          hosts: # Liste des serveurs de monitoring
            monitor01: # Premier serveur de monitoring
              ansible_host: ansible-lab-monitor01 # Nom du conteneur Docker
