# Inventaire PRODUCTION
all:
  vars:
    ansible_connection: docker
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3
    env: production

  children:
    production:
      children:
        webservers:
          hosts:
            web01:
              ansible_host: ansible-lab-web01
            web02:
              ansible_host: ansible-lab-web02
        
        appservers:
          hosts:
            app01:
              ansible_host: ansible-lab-app01
            app02:
              ansible_host: ansible-lab-app02
        
        databases:
          hosts:
            db01:
              ansible_host: ansible-lab-db01
        
        monitoring:
          hosts:
            monitor01:
              ansible_host: ansible-lab-monitor01
