# Inventaire STAGING
all: # Groupe racine contenant tous les serveurs
  vars: # Variables communes à tous les serveurs staging
    ansible_connection: docker # Type de connexion : Docker (pour environnement lab)
    ansible_user: root # Utilisateur de connexion : root
    #ansible_python_interpreter: /usr/bin/python3 # Interpréteur Python sur les hôtes cibles
    env: staging # Variable d'environnement : staging

  children: # Sous-groupes organisés par environnement
    staging: # Groupe staging
      children: # Sous-groupes fonctionnels dans staging
        webservers: # Groupe des serveurs web
          hosts: # Liste des serveurs web
            web01: # Premier serveur web
              ansible_host: ansible-lab-web01 # Nom du conteneur Docker
        
        appservers: # Groupe des serveurs d'application
          hosts: # Liste des serveurs d'application
            app01: # Premier serveur d'application
              ansible_host: ansible-lab-app01 # Nom du conteneur Docker
        
        monitoring: # Groupe des serveurs de monitoring
          hosts: # Liste des serveurs de monitoring
            monitor01: # Premier serveur de monitoring
              ansible_host: ansible-lab-monitor01 # Nom du conteneur Docker
