# Inventaire STAGING
all:
  vars:
    ansible_connection: docker
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3
    env: staging

  children:
    staging:
      children:
        webservers:
          hosts:
            web01:
              ansible_host: ansible-lab-web01
        
        appservers:
          hosts:
            app01:
              ansible_host: ansible-lab-app01
        
        monitoring:
          hosts:
            monitor01:
              ansible_host: ansible-lab-monitor01
